

version: '2.0'


services:

  front-end:
    container_name: frontEnd
    image: front-end
    build: ./UI
    # build:
    #   context: .
    #   dockerfile: ./UI/Dockerfile
    ports:
      - '4200:4200'
      - '80:80'
    volumes:
      - './UI/src:/usr/share/workdir/UI/src'
      - './UI/truffle:/usr/share/workdir/UI/truffle'

    command: bash -c "ls && node patch.js && ng build && cp nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
